name: CI

on:
  push:
    branches: [ "processeur" ]
  pull_request:
    branches: [ "processeur" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Installer build-essential et gcc
      - name: Install build-essential
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Compiler le programme
      - name: Build
        run: |
          docker build -t associativite_app .

      # Exécuter le programme
      - name: Run program
        run: |
          docker run --rm associativite_app > answer_associativity.txt 

      # Ajouter et pousser le fichier de résultats
      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git pull --force
          git add answer_associativity.txt
          git commit -m "Ajout des résultats d'associativité - $(date +'%Y-%m-%d %H:%M:%S')" || echo "Aucun changement à commit."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
