name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Installer build-essential et gcc
      - name: Install build-essential
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Compiler le programme
      - name: Build
        run: |
          gcc -o app associativity.c

      # Exécuter le programme
      - name: Run program
        run: |
          ./app  # Assurez-vous que cela génère le fichier answer_associativity.txt

      # Ajouter et pousser le fichier de résultats
      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add answer_associativity.txt
          git commit -m "Ajout des résultats d'associativité" || echo "Aucun changement à commit."
          # Récupérer les changements du dépôt distant
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
